### ISSUE TITLE
Whitespace cleanup after non-insert mode line manipulations

### ISSUE THREAD

**Issue by xileF1337** [thirtythreeforty/lessspace.vim#2]
Hi George,

thanks for your very useful VIM plugin. I started using it a while back to get rid of trailing whitespace, especially in code checked into version control systems. Though your plugin does help a lot, there are still a number of whitespace errors remaining. I think the main source of these, at least in my case, is the deletion of trailing parts of a line, e.g. comments. For example, consider a line like
`my $empty_string = "";        # the empty string`
where I later decide to remove the comment. I would usually do this by going to this line and hitting `f#d$`, which will remove the comment, but will not remove the whitespace after ";", yielding a whitespace error. 

Would it be possible to add support to your plugin for removing these types of whitespace errors, too? More precisely, I think it would be sensible to remove whitespace not just from all lines visited in insert mode, but also from all lines which have been manipulated by deletions (d), regexp substitutions or pastes. What do you think?

Regards,
Felix

**Comment by thirtythreeforty** [comment]
Glad you like the plugin!  I've noticed myself doing something similar to what you say as well.  Essentially the behavior boils down to noticing changes made in normal mode as well as insert mode, and performing the whitespace removal then too.

I think this is in principle doable, but I'm certain there are edge cases (just like there are with the existing insert mode behavior!).  The events `TextChanged` and `CursorMoved` are probably the interesting ones to watch.

I'll definitely look into this as time permits!

**Comment by thirtythreeforty** [comment]
Actually, I just learned about the `'[` and `']` marks, which are automatically placed at the beginning and end of each edited block.

This could allow me to implement this feature very easily.  Unfortunately it does not seem to handle all the corner cases of insert mode (like moving between lines with the arrow keys while in insert), so much of the existing code will have to stay.

**Comment by thirtythreeforty** [comment]
This is now implemented!
