### ISSUE TITLE
E16: Invalid range

### ISSUE THREAD

**Issue by fneu** [thirtythreeforty/lessspace.vim#4]
Thank you for an amazingly useful plugin!

Unfortunately I sometimes run into problems when **undoing** or **redoing** changes on the **last line** of a file. I'm not sure what types of changes cause this exactly, but I ran into this on several different occasions. It's mostly related to plugins and/or mappings I believe, but maybe it can occur on manual edits.

Just now it happened again so here is one way to reliably trigger this using the [vim-surround](https://github.com/tpope/vim-surround) plugin:

type a word into the last/only line of a file: 

```
this
is
the
last
line
```

with the cursor over `line`, type `ysiw"<esc>` to wrap it in quotation marks.

```
this
is
the
last
"line"
```

undoing this change with `u` triggers the error as well as redoing the change with `<c-r>`:

```
Error detected while processing function lessspace#OnTextChanged[15]..lessspace#
MaybeStripWhitespace:                                                           
line   13:                                                                      
E16: Invalid range: 5 , 6 s/\v\s+$//e                                           
Press ENTER or type command to continue      
```

The error message can be easily dismissed, but it would of course be preferable to not get the error :)
Maybe you can do something about this, thank you for your work in any case.

By the way I'm using lessspace with neovim v0.1.7 on linux.

**Comment by thirtythreeforty** [comment]
Thanks for the bug report, I can reproduce this, so it's not just your setup :).  I'll take a look; it's probably not hard to fix!

**Comment by thirtythreeforty** [comment]
Fixed, I was missing a clamp which shouldn't strictly be needed, but it doesn't hurt to have.  This may still have to do with the vagarities of repeat.vim, surround.vim, and friends, but if they cause this behavior, other plugins probably do it too, so it doesn't hurt to work around defensively.

Thanks for using; let me know if this doesn't fix it!

**Comment by fneu** [comment]
sorry for the delay, looks like it's all good now. Thanks!
