### ISSUE TITLE
Strips unchanged lines then can't undo changes

### ISSUE THREAD

**Issue by smitgd** [thirtythreeforty/lessspace.vim#7]
I edit a file with blanks at end of, for example, lines 5 and 10. If I change line 5 and remain in insert mode and move down with down-arrow to line 10 and, remaining in insert mode, move back to line 5 and then exit insert mode, the blanks at the end of 5 go away. But they also go away at line 10 (which I did not change at all). 
Ideally, only changed lines should have their trailing whitespace removed.
Then if I try to undo these changes, nothing happens. The change on line 5 won't undo and the blanks at the end of 5 and 10 won't come back. 
Only if I do command :LessSpace! to disable the plugin can I undo any previous changes.
(Hopefully I installed in right. I just put the entire cloned project lessspace.vim/ under ~/.vim/plugin/)

**Comment by thirtythreeforty** [comment]
Thanks for your report.  If the plugin is running, you installed it right.  It doesn't have any extra setup process like YouCompleteMe.

In the first case, I think LessSpace is functioning as intended; most users only stay in Insert mode when they actually intend to edit a line.  I would suggest leaving insert mode when you move lines... Not to tell you how to use your editor of course 😄.  It would also be a technical nightmare to track which lines were changed; the current implementation has to deal with newlines and it's already less-than-obvious.  I'm probably not going to implement that, sorry!  If you'd like to take a crack at it I'd be open to contributions though.

Not being able to undo is an unintended consequence of #2... LessSpace notices the undo normal-mode action and strips the changed lines, redoing what you were trying to undo.  To work around this, you can disable normal-mode stripping with
```
let g:lessspace_normal = 0
```

Of course it would be great if LessSpace would notice that the only difference in the changed lines is stripped whitespace, and not reapply its changes (more "do what I mean" edge cases).  That way you could leave normal mode editing turned on and still be able to get back to an unedited file.  I need to think about how to implement that, but I think it should be doable.

**Comment by thirtythreeforty** [comment]
Actually I think "undo" should mean "undo" -- LessSpace should not do anything at all when the user presses undo, to put the line back how it was found, in both insert mode and normal mode edits.  The stripping should ideally be rolled into the user's action (insert mode stripping already is, but I'm not sure if normal mode stripping is or not).  That way the undo cover's LessSpace's changes and whatever the user's action was.

**Comment by smitgd** [comment]
Thanks  for the quick reply. Yes, I discovered that if I disable the normal mode strip it allows undo. However, I frequently go to near end of lines and hit D in normal mode and blanks at end sometimes remain. Having this feature remove the blanks is very helpful but not being able to undo is a showstopper for me. 
Yes, I almost always move around in normal mode  so having unchanged line stripped is not a big deal.

**Comment by thirtythreeforty** [comment]
OK please try the commit I just pushed.  It should prevent whitespace stripping when undos have been made.

**Comment by smitgd** [comment]
That fixed it. Thanks for the very good plugin! The show is back on :).
There is another plugin discussed here
http://vi.stackexchange.com/questions/8029/from-a-textchanged-autocommand-event-how-to-get-the-range-that-has-been-changed  
and obtained here https://github.com/tweekmonster/wstrip-changed.vim
This also seems to work in both normal and insert modes. However, it uses the "diff" command to compare before and after states of the buffer. I don't really understand how it works. Not sure how portable the diff command is (I only use gvim on linux or gvim in cygwin, so diff exists there). I don't see any lag because of the diff when I use the plugin. The discussion mentions something about duplicate lines being a problem which I don't really understand. Anyhow, just thought you might be interested to see a different approach to the same problem. Thanks again!   --gene

**Comment by thirtythreeforty** [comment]
Thanks for the link! That's actually a really cool approach.  The only
thing I don't like about it is that `diff` may not be all that portable.
But overall it could end up being a very flexible plugin.
