### ISSUE TITLE
Does not work well together vim-multiple-cursors

### ISSUE THREAD

**Issue by Leandros** [thirtythreeforty/lessspace.vim#8]
In a [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors) selection, adding trailing whitespace is impossible, due to being stripped immediately by lessspace.

**Comment by thirtythreeforty** [comment]
Hmmm that sucks, although it doesn't surprise me.  I take it that "multiple cursors" *isn't* actually multiple points and they just keep a list of cursor positions internally.  So yeah, makes sense that LessSpace won't know where the extra locations are.

I'd be happy adding an integration if possible.  Ideally stripping would ignore all the changed lines. Unfortunately, reading through their documentation it doesn't look like they have a (stable) way to learn where the multiple cursors are.

Of course, the easy way out is to just use their `autocmd` hooks to disable LessSpace for the duration of the multiple cursor session.  This would be better than nothing, but it would probably surprise users who expect "multiple cursors" to mean multiple cursors.

I'm open to suggestions. Thoughts?

**Comment by Leandros** [comment]
> Of course, the easy way out is to just use their `autocmd` hooks to disable LessSpace for the duration of the multiple cursor session.

Making that an option sounds like a great and simple start, considering that the amount of users encountering this might be rather low.
Do you know if multiple cursors allows you to get the range of the selection? Wouldn't it be a simple solution to run stripping over the whole range once exited?

**Comment by thirtythreeforty** [comment]
> Making that an option sounds like a great and simple start

That's true, and it's not like I can't improve support later. I'll see if I can get that working.

> Do you know if multiple cursors allows you to get the range of the selection? Wouldn't it be a simple solution to run stripping over the whole range once exited?

Ideally they would provide a way to get ahold of a list of cursor locations.  Then LessSpace would do its thing on each line that it reported (basically ignoring changes to them in insert mode, and cleaning them when the user exited back to normal mode).

But I don't see a way to detect cursor locations at all. I could do some hacky stuff involving intercepting Ctrl-n, but that's prone to breakage and I'd rather not.

**Comment by Leandros** [comment]
> That's true, and it's not like I can't improve support later. I'll see if I can get that working.

Awesome! Thanks a lot!

**Comment by thirtythreeforty** [comment]
@Leandros could you try the `issue-8-multiple-cursors` branch to see if it works for you?

**Comment by thirtythreeforty** [comment]
I'm gonna go ahead and merge this (Works For Me™), but let me know if you notice any more trouble!

**Comment by Leandros** [comment]
Sorry, I was busy. Works, to the extend that if I add whitespace at the end of the line while in multi-cursor mode, it'll only be stripped for one of the selected lines, not all. Though, I don't think it's much of a problem.
